name: "release"

on:
  push:
    branches:
      - "main"

jobs:
  pre-release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: "Build"
        run: cargo build --release

      - name: "Strip and rename"
        run: strip target/release/radius -o target/release/radius-git-${{ github.sha }}

      - uses: ncipollo/release-action@v1
        with:
          tag: "0.1.0"
          artifacts: target/release/radius-git-${{ github.sha }}
